version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - my-network
    ports:
      - "8001:8000"
    working_dir: /code
    volumes:
      - ${PWD}:/code
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=crud_db
  postgres:
    image: postgres:14-alpine
    networks:
      - my-network
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=crud_db
networks:
  my-network:
    driver: bridge

  
