FROM python:3.12-slim as builder

WORKDIR /code

COPY requirements.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt



COPY . .

FROM builder as run

WORKDIR /code

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

COPY --from=builder /code/main.py .

#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

ENTRYPOINT uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}