apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: crud-app
          image: joty46/crud-app-set-env:v1
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              value: 'postgres'
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: crud_db
            - name: DB_PASSWORD
              value: '1234'